name: 'rp'
stage1_ckpt:  None
restore_ckpt: None
depth_ckpt: None
lr: 0.0001
wdecay: 1e-5
batch_size: 1
stage_1_num_steps: 200000
depth_refine_num_steps: 20000
stage_2_num_steps: 200000
coarse_vox_size: 0.01

dataset:
  source_id: [0, 1]
  train_novel_id: [2, 3, 4]
  val_novel_id: [3]
  use_hr_img: False
  use_processed_data: True
  data_root: './renderpeople'
  training_view_num: 36
  ref_view: [0,9,18,27]
  ref_view_num: 4
  valid_ref_view_num: 4
  ratio: 1.0
  bg_color: [0.0,0.0,0.0]
model:
  encoder:
    gsnet:
      encoder_dims: [32, 48, 96]
      decoder_dims: [48, 64, 96]
      parm_head_dim: 32

record:
  loss_freq: 5000
  eval_freq: 5000
